cc_binary(
    name = "aoc",
    srcs = [
        "main.cc",
    ],
    deps = [
        "@com_google_absl//absl/flags:flag",
        "@com_google_absl//absl/flags:parse",
        "@com_google_absl//absl/strings"
    ],
)
